# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# Change the following value to '/PROJECT_NAME' ONLY IF your site type is GitHub Pages Project sites
# and doesn't have a custom domain.
baseurl:

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: de-DE

# Additional parameters for datetime localization, optional. › https://github.com/iamkun/dayjs/tree/dev/src/locale
prefer_datetime_locale:

# Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: Europe/Berlin

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: CityPulse News                          # the main title

tagline: Aktuelle Meldungen 📰 | Verkehrsinfos 🚦 | Wettervorhersagen ☀️ | Dein Stadtpuls ♥️ | Immer informiert, immer voraus

description: >-                        # used by seo meta and the atom feed
 Willkommen bei CityPulse News – Ihrem Onlinemagazin für Nachrichten, Verkehrsinformationen
 und Wettervorhersagen. Wir halten Sie stets informiert und begleiten Sie durch den Puls
 Ihrer Stadt. Beachten Sie bitte, dass CityPulse News lediglich ein Freizeitprojekt ist,
 um den Static-Page-Generator Jekyll besser kennenzulernen. Die vor vorzufindenen Inhalte
 werden mithilfe von Künstlicher Intelligenz erstellt. Die Korrektheit, Akualität und
 Vertrauenswürdigkeit dieser Nachrichten ist unter keinen Umständen gewährleistet.

# fill in the protocol & hostname for your site, e.g., 'https://username.github.io'
url:

github:
  username: 2000Arion
twitter:
  username: Arion2000TV
patreon:
  username: arion2000
twitch:
  username: arion2000
discord:
  invitelink: D3UVPKseD8
youtube:
  channelid: UCtoUWgrspY7LZqikStKkgaQ
social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: a2data
  email: cpn-redaktion@arion2000.xyz             # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://arion2000.xyz     
    - https://r.arion2000.xyz/github


# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

# Web Analytics Settings
analytics:
  google:
    id: 'G-MWH5CHGDZZ'          # Fill with your Google Analytics ID
  goatcounter:
    id: # fill in your GoatCounter ID

# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light  - Use the light color scheme
#     dark   - Use the dark color scheme
#
# theme_mode: dark # [light | dark]

# The CDN endpoint for images.
# Notice that once it is assigned, the CDN url
# will be added to all image (site avatar & posts' images) paths starting with '/'
#
# e.g. 'https://cdn.com'
img_cdn:

# the avatar on sidebar, support local or CORS resources
avatar: 'https://pinboard-uploads-production.operacdn.com/images/5e5e615d-08de-4368-aff0-1b83b8e0dcb0/d7aedb01-19b6-4b57-997e-3127c9ca8f7e/64c18a39-090b-4318-99ca-66432a746abe.png'

# boolean type, the global switch for ToC in posts.
toc: true

comments:
  active: giscus        # The global switch for posts comments, e.g., 'disqus'.  Keep it empty means disable
  # The active options are as follows:
  disqus:
    shortname:    # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo:         # <gh-username>/<repo>
    issue_term:   # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  giscus:
    repo: 200Arion/jekyll-news-blog
    repo_id: R_kgDOLeVVZQ
    category: Kommentare
    category_id: DIC_kwDOLeVVZc4Cd3b4
    mapping: pathname
    strict: 0
    emit_metadata: 1
    input_position: top
    lang: de
    data_loading: lazy
    crossorigin: anonymous
    reactions_enabled: 1

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: true     # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
    env:          # [development|production]

pwa:
  enabled: true # the option for PWA feature (installable)
  cache:
    enabled: true # the option for PWA offline cache
    # Paths defined here will be excluded from the PWA cache.
    # Usually its value is the `baseurl` of another website that
    # shares the same domain name as the current website.
    deny_paths:
      # - "/example"  # URLs match `<SITE_URL>/example/*` will not be cached by the PWA

paginate: 10

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - rollup.config.js
  - node_modules
  - package*.json
  - archive_old
  - template
  - reference_files
  - kubernetes
  - Dockerfile

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
