name: 'Pull Request'
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - CODE_OF_CONDUCT.md
      - LICENSE

jobs:
  pull-request:

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

        with:
          fetch-depth: 0  # for posts's lastmod

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Test Site
        run: bash tools/test.sh
        env:
          JEKYLL_ENV: production

